version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile.server
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: "mongodb+srv://bharathikannaa:bharathikannaa@aquaswift.1njv0ij.mongodb.net/aquaswift?retryWrites=true&w=majority&appName=AquaSwift"
  nginx:
    build:
      context: .
      dockerfile: DockerFile.nginx
    ports:
      - '80:80'
    depends_on:
      - backend
