FROM node:20-alpine AS client-build
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY tsconfig.base.json ./tsconfig.base.json
COPY client ./client

RUN pnpm install --prefix ./client && pnpm --prefix ./client run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=client-build /app/client/dist /usr/share/nginx/html
