FROM node:18
WORKDIR /app
COPY client ./client
RUN cd client && pnpm install && pnpm build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/client/dist /usr/share/nginx/html
