services:
  - type: web
    name: aquaswift-frontend
    env: docker
    plan: free
    dockerfilePath: DockerFile.nginx
    buildFilter:
      paths:
        - client/**/*
        - DockerFile.nginx
        - nginx.conf
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  - type: web
    name: aquaswift-backend
    env: docker
    plan: free
    dockerfilePath: DockerFile.server
    buildFilter:
      paths:
        - server/**/*
        - DockerFile.server
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /api/health
