services:
  - type: web
    name: aquaswift-frontend
    env: docker
    plan: free
    dockerfilePath: DockerFile.nginx
    buildFilter:
      paths:
        - client/**/*
        - DockerFile.nginx
        - nginx.conf
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  - type: web
    name: aquaswift-backend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/index.ts
    rootDir: server
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
