# Later usages:
name: AquaSwift CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
      - 'server/**'
      - '.github/**'
      - 'Dockerfile*'
      - 'pnpm-workspace.yaml'

jobs:
  setup:
    name: Install & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install
      - name: Lint all
        run: pnpm lint

  test-client:
    name: Client Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3

        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Run Client Tests
        run: pnpm test --filter client
  test-server:
    name: Server Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Run Server Tests
        run: pnpm test --filter server
  build-client:
    name: Build Client Docker Image
    needs: [test-client, test-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t aquaswift-client -f DockerFile.nginx .
  build-server:
    name: Build Server Docker Image
    needs: [test-client, test-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t aquaswift-server -f DockerFile.server .
  deploy:
    name: Deploy to Render
    needs: [build-client, build-server]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}

      - name: Deploy Backend to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
